---
# Install core OpenStack components
#- name: (OS-COMMON) install Ubuntu-Cloud-Keyring
#  package: name=ubuntu-cloud-keyring state=present
#
#- name: (OS-COMMON) add Kilo repo
#  lineinfile:
#    line: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/newton main"
#    dest: /etc/apt/sources.list.d/cloudarchive-newton.list
#    create: yes
#    state: present

- name: (OS-COMMON) add newton repo
  command: "add-apt-repository cloud-archive:newton"

- name: (OS-COMMON) update cache and perform upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: (OS-COMMON) install python openstack client
  apt: 
    name: "{{ item }}" 
    state: present
    default_release: xenial-updates/newton
  with_items:
    - python-openstackclient
  tags: base-packages