heat_template_version: 2013-05-23

description: Template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: Ubuntu 16.04  
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: test

resources:
  default_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: shared
      user_data: |
        #!/bin/sh
        echo "Hello, World!"
      user_data_format: RAW

outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [default_instance, name] }
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [default_instance, first_address] }
