- name: (CLOUDLET) install fabric/openssh/git
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - fabric
    - git
    - openssh-server

- name: (CLOUDLET) checkout elijah-provisioning code from github
  git:
    repo: https://github.com/cmusatyalab/elijah-provisioning.git
    dest: ~/elijah-provisioning

- name: (CLOUDLET) install library using fabric
  shell: fab install
  args:
    chdir: ~/elijah-provisioning


# - name: (CLOUDLET) install cloudlet library
#   expect:
#     command: fab install
#     chdir: ~/elijah-provisioning
#     responses:
#       [localhost] Login password for 'root': "{{localuser_pw}}"
#   become: true
#   become_user: "{{localuser}}"

