- name: setup ipv4 sysctl params
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      net.ipv4.conf.all.rp_filter=0
      net.ipv4.conf.default.rp_filter=0
      net.bridge.bridge-nf-call-iptables=1
      net.bridge.bridge-nf-call-ip6tables=1

- name: push sysctl changes
  command: sysctl -p

- name: install networking components
  apt:
    name: "{{ item }}"
    state: present
    default_release: trusty-updates/kilo
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent

- name: (COMPUTE) replace neutron.conf
  template: src=neutron.conf.j2 dest="/etc/neutron/neutron.conf" owner=root group=root mode=0644

- name: (COMPUTE) replace linuxbridge_agent.ini
  template: src=linuxbridge_agent.ini.j2 dest="/etc/neutron/plugins/ml2/linuxbridge_agent.ini" owner=root group=root mode=0644

- name: replace ml2_conf.ini
  template: src=ml2_conf.ini.j2 dest="/etc/neutron/plugins/ml2/ml2_conf.ini" owner=root group=root mode=0644
  notify: restart openvswitch
